"""empty message

Revision ID: 41497b24fa6e
Revises: 963b706f6f92
Create Date: 2017-11-29 14:06:19.447330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41497b24fa6e'
down_revision = '963b706f6f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.drop_column('wkt_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample__site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wkt_location', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
