"""empty message

Revision ID: 757789afe568
Revises: 94f1dc05a972
Create Date: 2017-11-29 13:09:30.625605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757789afe568'
down_revision = '94f1dc05a972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wkb_boundary', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('wkt_boundary_bin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wkt_boundary_bin', sa.BLOB(), nullable=True))
        batch_op.drop_column('wkb_boundary')

    # ### end Alembic commands ###
