"""empty message

Revision ID: 94f1dc05a972
Revises: b4774151ff34
Create Date: 2017-11-29 13:05:04.143121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f1dc05a972'
down_revision = 'b4774151ff34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wkt_boundary_bin', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        batch_op.drop_column('wkt_boundary_bin')

    # ### end Alembic commands ###
