"""empty message

Revision ID: 988d86fa4051
Revises: 
Create Date: 2017-11-28 09:43:17.388150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988d86fa4051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('sample__site__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('sample_date', sa.String(length=32), nullable=True),
    sa.Column('sample_value', sa.Float(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'sample__site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_date')
    )
    with op.batch_alter_table('boundary', schema=None) as batch_op:
        #batch_op.add_column(u'boundary', sa.Column('project_site_id', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key('project_site_id', 'boundary', 'project_area', ['project_site_id'], ['id'])
        batch_op.create_foreign_key('project_site_id', 'project_area', ['project_site_id'], ['id'])

    op.add_column(u'sample__site', sa.Column('has_current_advisory', sa.Boolean(), nullable=True))
    op.add_column(u'sample__site', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column(u'sample__site', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column(u'sample__site', sa.Column('temporary_site', sa.Boolean(), nullable=True))
    with op.batch_alter_table('site_message', schema=None) as batch_op:
        batch_op.create_unique_constraint('site_id', ['site_id'])

    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('row_entry_date', sa.String(length=32), nullable=True))
    op.add_column(u'user', sa.Column('row_update_date', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'row_update_date')
    op.drop_column(u'user', 'row_entry_date')
    op.drop_column(u'user', 'active')
    op.drop_constraint(None, 'site_message', type_='unique')
    op.drop_column(u'sample__site', 'temporary_site')
    op.drop_column(u'sample__site', 'longitude')
    op.drop_column(u'sample__site', 'latitude')
    op.drop_column(u'sample__site', 'has_current_advisory')
    op.drop_constraint(None, 'boundary', type_='foreignkey')
    op.drop_column(u'boundary', 'project_site_id')
    op.drop_table('sample__site__data')
    op.drop_table('roles_users')
    op.drop_table('role')
    # ### end Alembic commands ###
