"""empty message

Revision ID: b8ac3dbaa2da
Revises: 9e2f1adfc1b2
Create Date: 2018-05-30 14:55:44.696036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ac3dbaa2da'
down_revision = '9e2f1adfc1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample__site__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_entry_date', sa.String(length=32), nullable=True),
    sa.Column('row_update_date', sa.String(length=32), nullable=True),
    sa.Column('sample_date', sa.String(length=32), nullable=True),
    sa.Column('sample_value', sa.Float(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'sample__site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'sample_date', name='sample_site_data_uc1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample__site__data')
    # ### end Alembic commands ###
